### ISSUE TITLE
Request for the loading function of the dataset `vessel_ais`

### ISSUE THREAD

**Issue by xuliang97** [WenjieDu/BenchPOTS#11]
Could you provide the pre-processing script of `vessel_ais` dataset? Thank you for your reply.

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to PyPOTS! You can [follow me](https://github.com/WenjieDu) on GitHub 
to receive the latest news of PyPOTS. If you find PyPOTS helpful to your work, please star⭐️ this repository.
Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community.
It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie

**Comment by WenjieDu** [comment]
Hi @xuliang97, thanks for your interest in `vessel_ais` dataset. This dataset is contributed by [Luka Grgičević](https://github.com/GrgicevicLukaNTNU) from NTNU, who currently is not active in the PyPOTS community. I'll ping him to see if he'd like to contribute to the detailed preprocessing function of this dataset. By the way, you can follow me to get notified of updates on all PyPOTS toolkits in the future.

If our work is helpful to you, please star our repos to make more people notice them ;-)

**Comment by WenjieDu** [comment]
Hi Luka @GrgicevicLukaNTNU, will you be able to write a preprocessing function like others in BenchPOTS for your `vessel_ais` dataset?

**Comment by GrgicevicLukaNTNU** [comment]
Hi @WenjieDu, I won't be able to follow this project anymore. The script is [here](https://github.com/WenjieDu/TSDB/blob/main/tsdb/loading_funcs/vessel_ais.py), so I guess the user could continue from there and modify it as needed. Best regards
